### ISSUE TITLE
Language server ClassCastException in custom Flex skin component

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#203]
I have created custom skin based on spark ScrollerSkin. I just copied all content from original skin to new one. When I open my class and roll over on `<fx:Component` or even scroll to that I'm getting `ClassCastException`.  

In VSCode with extension 0.10.0 I'm getting a bit different exception. It is enough to open that file and click on `id` of `<fx:Component`

I have prepared some gifs :)

![castclassexception](https://user-images.githubusercontent.com/24554795/37396782-2c41d43c-277a-11e8-84ca-dcd427e11c29.gif)

![castclassexception_vscode](https://user-images.githubusercontent.com/24554795/37396788-2f18d926-277a-11e8-957c-fb9928d2f854.gif)

**Project:** [ClassCastExceptionTest.zip](https://github.com/prominic/Moonshine-IDE/files/1810509/ClassCastExceptionTest.zip)

**Moonshine Exception:**
```
: Moonshine IDE 1.10.0
: Source code is under Apache License, Version 2.0
: https://github.com/prominic/Moonshine-IDE
: Uses as3abc (LGPL), as3swf (MIT), fzip (ZLIB), asblocks (Apache License 2.0), NativeApplicationUpdater (LGPL)
: Running on Adobe AIR 28.0.0.127
: Mar 14, 2018 11:04:29 AM org.xsocket.connection.Server$LifeCycleHandler onConnected
: INFO: server listening on 0:0:0:0:0:0:0:0:64602 (xSocket 2.8.15)
: java.lang.ClassCastException: org.apache.royale.compiler.internal.definitions.InterfaceDefinition cannot be cast to org.apache.royale.compiler.definitions.IClassDefinition
: 	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.getEmbeddedActionScriptNodeInMXMLTag(ActionScriptTextDocumentService.java:5477)
: 	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.hover(ActionScriptTextDocumentService.java:454)
: 	at moonshine.xSocketDataHandler.onData(xSocketDataHandler.java:226)
: 	at org.xsocket.connection.HandlerAdapter.performOnData(HandlerAdapter.java:242)
: 	at org.xsocket.connection.HandlerAdapter.access$200(HandlerAdapter.java:42)
: 	at org.xsocket.connection.HandlerAdapter$PerformOnDataTask.run(HandlerAdapter.java:210)
: 	at org.xsocket.SerializedTaskQueue.performPendingTasks(SerializedTaskQueue.java:161)
: 	at org.xsocket.SerializedTaskQueue.access$100(SerializedTaskQueue.java:40)
: 	at org.xsocket.SerializedTaskQueue$MultithreadedTaskProcessor.run(SerializedTaskQueue.java:189)
: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
: 	at java.lang.Thread.run(Thread.java:748)
: java.lang.ClassCastException: org.apache.royale.compiler.internal.definitions.InterfaceDefinition cannot be cast to org.apache.royale.compiler.definitions.IClassDefinition
: 	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.getEmbeddedActionScriptNodeInMXMLTag(ActionScriptTextDocumentService.java:5477)
: 	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.hover(ActionScriptTextDocumentService.java:454)
: 	at moonshine.xSocketDataHandler.onData(xSocketDataHandler.java:226)
: 	at org.xsocket.connection.HandlerAdapter.performOnData(HandlerAdapter.java:242)
: 	at org.xsocket.connection.HandlerAdapter.access$200(HandlerAdapter.java:42)
: 	at org.xsocket.connection.HandlerAdapter$PerformOnDataTask.run(HandlerAdapter.java:210)
: 	at org.xsocket.SerializedTaskQueue.performPendingTasks(SerializedTaskQueue.java:161)
: 	at org.xsocket.SerializedTaskQueue.access$100(SerializedTaskQueue.java:40)
: 	at org.xsocket.SerializedTaskQueue$MultithreadedTaskProcessor.run(SerializedTaskQueue.java:189)
: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
: 	at java.lang.Thread.run(Thread.java:748)
```

**VSCode Exception:**

```
Mar 14, 2018 11:20:26 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint lambda$static$0
SEVERE: Internal error: java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:53)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:105)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:210)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:146)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:149)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:84)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:51)
	... 11 more
Caused by: java.lang.ClassCastException: org.apache.royale.compiler.internal.definitions.InterfaceDefinition cannot be cast to org.apache.royale.compiler.definitions.IClassDefinition
	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.getEmbeddedActionScriptNodeInMXMLTag(ActionScriptTextDocumentService.java:5461)
	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.hover(ActionScriptTextDocumentService.java:457)
	... 16 more

[Error - 11:20:26 AM] Request textDocument/hover failed.
  Message: Internal error.
  Code: -32603 
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:53)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:105)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:210)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:146)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:149)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:84)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:51)
	... 11 more
Caused by: java.lang.ClassCastException: org.apache.royale.compiler.internal.definitions.InterfaceDefinition cannot be cast to org.apache.royale.compiler.definitions.IClassDefinition
	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.getEmbeddedActionScriptNodeInMXMLTag(ActionScriptTextDocumentService.java:5461)
	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.hover(ActionScriptTextDocumentService.java:457)
	... 16 more

Mar 14, 2018 11:20:28 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint lambda$static$0
SEVERE: Internal error: java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:53)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:105)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:210)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:146)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:149)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:84)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:51)
	... 11 more
Caused by: java.lang.ClassCastException: org.apache.royale.compiler.internal.definitions.InterfaceDefinition cannot be cast to org.apache.royale.compiler.definitions.IClassDefinition
	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.getEmbeddedActionScriptNodeInMXMLTag(ActionScriptTextDocumentService.java:5461)
	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.hover(ActionScriptTextDocumentService.java:457)
	... 16 more

[Error - 11:20:28 AM] Request textDocument/hover failed.
  Message: Internal error.
  Code: -32603 
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:53)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:105)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:210)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:146)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:149)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:84)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:51)
	... 11 more
Caused by: java.lang.ClassCastException: org.apache.royale.compiler.internal.definitions.InterfaceDefinition cannot be cast to org.apache.royale.compiler.definitions.IClassDefinition
	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.getEmbeddedActionScriptNodeInMXMLTag(ActionScriptTextDocumentService.java:5461)
	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.hover(ActionScriptTextDocumentService.java:457)
	... 16 more
```

**Comment by piotrzarzycki21** [comment]
I have tested it with your update and it's fixed.
