### ISSUE TITLE
Full integration with language server build system

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#231]
Starting from Language Server [0.11.0](https://github.com/BowlerHatLLC/vscode-nextgenas/blob/v0.11.0/distribution/src/assembly/CHANGELOG.md#0110) @joshtynjala added new feature allows faster build all supported SDK.

I would like to fully integrate with that API in order to completely remove classes responsible for current process of building ([MXMLCJavaScriptPlugin](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/as3project/mxmlc/MXMLCJavaScriptPlugin.as), [MXMLCPlugin](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/as3project/mxmlc/MXMLCPlugin.as)).

**Comment by rat-moonshine** [comment]
@piotrzarzycki21 can you provide some more documentation and the plan of yours, before actually going to modify on this area?

**Comment by piotrzarzycki21** [comment]
@rat-moonshine In case of implementation I don't have any plan. I asked Josh on Patreon in one of his post about that whether we can use it in Moonshine. He said that API is available and we can. I will explore it and give here more details.

Definitely I will do everything on the separate branch!

**Comment by joshtynjala** [comment]
Since my earlier reply, I've determined that the language server will need some additional modifications before Moonshine can use its new "quick build" command.

I need to do the following:

* Make the configuration more modular. Currently, it requires the presence of an *asconfig.json* file.
* Add support for release builds. Currently, it can only create debug builds.

**Comment by piotrzarzycki21** [comment]
I would like to work on that using an idea of generating temporary asconfig.json file and run build trough Language server. Some discussion is in #427 and https://github.com/prominic/Moonshine-IDE/issues/427#issuecomment-455724422

Just to be clear it would be primary system for building, but if it's fail on some stage I will switch the previous one.

**Comment by piotrzarzycki21** [comment]
@joshtynjala I have started working on using language server to build Flex project. I'm currently in a step where I was able to launch asconfig.jar and init compilation, but for some reason I'm getting following error.

```
: Compiling NewFlexDesktopProject
: Command: java -jar "C:\Program Files (x86)\Moonshine\elements\as3mxml-language-server\bin\asconfigc.jar" --sdk C:\MoonshineSDKs\Royale_SDK\apache-royale-0.9.7-bin-js\royale-asjs +configname=air -debug=true --project D:\Work\projects\Prominic.NET\MoonshineTests\NewFlexDesktopProject\obj\NewFlexDesktopProject.json
: Adobe AIR application descriptor not found: D:\Work\projects\Prominic.NET\MoonshineTests\NewFlexDesktopProject\obj\src\NewFlexDesktopProject-app.xml
: Compilation of NewFlexDesktopProject finished.
```

I cannot understand why LS searching descriptor file inside `\obj\src` instead `src\`. Is it related to de fact that I'm writing asconfig.json file to `obj\` folder ? I'm attaching Flex desktop project - in order to test it you need to use my branch [features/issue_231_integration_with_language_server](https://github.com/prominic/Moonshine-IDE/tree/features/issue_231_integration_with_language_server) and use `Project` -> `Build Project`

**Comment by joshtynjala** [comment]
> I cannot understand why LS searching descriptor file inside \obj\src instead src\. Is it related to de fact that I'm writing asconfig.json file to obj\ folder ?

Yes, asconfigc sets the current working directory to the directory containing the asconfig.json file. So your paths need to be relative to obj.

**Comment by piotrzarzycki21** [comment]
> > I cannot understand why LS searching descriptor file inside \obj\src instead src. Is it related to de fact that I'm writing asconfig.json file to obj\ folder ?
> 
> Yes, asconfigc sets the current working directory to the directory containing the asconfig.json file. So your paths need to be relative to obj.

Ok, so I don't have to much of a choice than write that file in the project folder directly instead in obj

**Comment by joshtynjala** [comment]
You can write it in obj. You just need adjust any relative paths that appear in the asconfig.json file, like source-path and library-path in the compilerOptions section. Or you could make sure to always use absolute paths.

**Comment by piotrzarzycki21** [comment]
> You can write it in obj. You just need adjust any relative paths that appear in the asconfig.json file, like source-path and library-path in the compilerOptions section. Or you could make sure to always use absolute paths.

I'm not sure if it's ok, but I have changed command to something like that and getting different error. Anyway I will experiment with all of that.

```
: Compiling NewFlexDesktopProject
: Command: java -jar "D:\Work\projects\Prominic.NET\Moonshine-IDE\ide\MoonshineDESKTOPevolved\bin-debug\elements\as3mxml-language-server\bin\asconfigc.jar" --sdk D:\Work\flex-sdk-4.16.1_adobe_air_32 +configname=air -debug=true --project obj/NewFlexDesktopProject.json
: Exception in thread "main" java.lang.AssertionError: Default directory is not an absolute path
: 	at sun.nio.fs.WindowsFileSystem.<init>(WindowsFileSystem.java:61)
: 	at sun.nio.fs.WindowsFileSystemProvider.<init>(WindowsFileSystemProvider.java:53)
: 	at sun.nio.fs.DefaultFileSystemProvider.create(DefaultFileSystemProvider.java:36)
: 	at java.nio.file.FileSystems$DefaultFileSystemHolder.getDefaultProvider(FileSystems.java:108)
: 	at java.nio.file.FileSystems$DefaultFileSystemHolder.access$000(FileSystems.java:89)
: 	at java.nio.file.FileSystems$DefaultFileSystemHolder$1.run(FileSystems.java:98)
: 	at java.nio.file.FileSystems$DefaultFileSystemHolder$1.run(FileSystems.java:96)
: 	at java.security.AccessController.doPrivileged(AccessController.java:647)
: 	at java.nio.file.FileSystems$DefaultFileSystemHolder.defaultFileSystem(FileSystems.java:96)
: 	at java.nio.file.FileSystems$DefaultFileSystemHolder.<clinit>(FileSystems.java:90)
: 	at java.nio.file.FileSystems.getDefault(FileSystems.java:176)
: 	at java.io.File.toPath(File.java:2234)
: 	at com.as3mxml.asconfigc.ASConfigC.loadConfigFromFileWithSchema(ASConfigC.java:326)
: 	at com.as3mxml.asconfigc.ASConfigC.loadConfigFromFile(ASConfigC.java:310)
: 	at com.as3mxml.asconfigc.ASConfigC.<init>(ASConfigC.java:217)
: 	at com.as3mxml.asconfigc.ASConfigC.main(ASConfigC.java:194)
: Compilation of NewFlexDesktopProject finished.
```

**Comment by joshtynjala** [comment]
In VSCode, it appears that I pass in the absolute path to asconfig.json. Most likely, I never bothered to handle relative paths with --project in this version of asconfigc.

**Comment by piotrzarzycki21** [comment]
@joshtynjala It turns out after yesterdays discussion on a call we would like to have project created and configured in Moonshine compatible with VSCode if possible. In that case I would write down that file in the root folder of the project. I will try to take care of that file if it is already exists. If you have thoughts against that please let me know.

**Comment by piotrzarzycki21** [comment]
@joshtynjala I was able to use asconfigc.jar to build Flex desktop app, but for some reason I'm not able to run it and I cannot figure out why. When I'm running Moonshine from my IDE and build Flex project - sometimes it's able to run, but it is very random. In case of installed version of Moonshine Flex app didn't run at all. Console output indicates that everything should be fine and I have temporary added a bit more to that. 

```
: Compiling NewFlexDesktopProject
: Command: "C:\Program Files\Java\jdk8u202-b08\bin\javaw.exe" -jar "C:\Program Files (x86)\Moonshine\elements\as3mxml-language-server\bin\asconfigc.jar" --sdk D:\Work\flex-sdk-4.16.1_adobe_air_32 --debug=true --project D:\Work\projects\Prominic.NET\MoonshineTests\NewFlexDesktopProject\NewFlexDesktopProject-asconfig.json
: Loading configuration file D:\Work\flex-sdk-4.16.1_adobe_air_32\frameworks\air-config.xml
: Loading configuration file D:\Work\projects\Prominic.NET\MoonshineTests\NewFlexDesktopProject\obj\NewFlexDesktopProjectConfig.xml
: D:\Work\projects\Prominic.NET\MoonshineTests\NewFlexDesktopProject\bin-debug\NewFlexDesktopProject.swf (1007639 bytes)
: Project Build Successfully.
: Launch object: name Moonshine SWF Launch, noDebug: true, program: bin-debug\NewFlexDesktopProject-app.xml
: Launching application: NewFlexDesktopProject
: Compilation of NewFlexDesktopProject finished.
```

I gave @Aszusz build of Moonshine to check on his PC and he reported more disturbing information. Application on his PC is trying to launch but it's throwing an error. 
![86810839_2313898615576145_5339715702750183424_n](https://user-images.githubusercontent.com/24554795/74669061-b61d0e80-51a6-11ea-97e5-c5ccf15e5495.png)
![86826131_1032303173808943_4855847702249865216_n](https://user-images.githubusercontent.com/24554795/74669064-b74e3b80-51a6-11ea-9632-6ac4a7530312.png)
![87045181_503161867010299_7541341652648984576_n](https://user-images.githubusercontent.com/24554795/74669066-b74e3b80-51a6-11ea-8b98-139193cb678b.png)

**Scenario:**
1. Create Flex desktop application
2. Choose in menu **Project** -> **Build & Run**

**Comment by piotrzarzycki21** [comment]
@joshtynjala I think I know what is wrong. I have build project using Moonshine, than jump to VSCode and tried to run it. 
1. When I used **Run without Debugging** - nothing happened - same as in Moonshine
2. When I used **Start Debugging** I got prompt:

![commits](https://user-images.githubusercontent.com/24554795/74749631-bd0d5500-526a-11ea-93d7-68e4b6cab8f0.png)

I'm wondering why first option didn't prompt me with anything at all.

**Comment by joshtynjala** [comment]
I'll see if I can find a way to report an error when Run without Debugging fails to launch.

**Comment by piotrzarzycki21** [comment]
> I'll see if I can find a way to report an error when Run without Debugging fails to launch.

I have pushed fix to make sure that app descriptor is correct when user create new Flex desktop app, but now I'm able to reproduce @Aszusz issue. I'm not sure what is happening in that case.

**Comment by joshtynjala** [comment]
When you run asconfigc, you can pass the --verbose option to show more detailed output. This should allow you to compare the compiler options that asconfigc is using versus the ones that the old Moonshine compile task uses.

**Comment by piotrzarzycki21** [comment]
> When you run asconfigc, you can pass the --verbose option to show more detailed output. This should allow you to compare the compiler options that asconfigc is using versus the ones that the old Moonshine compile task uses.

Thanks for that! It seems to be too late for me. I have found that in case of old code there have been used parameter "-o nameofthefile.swf" - Is it necessary to use it when I'm using your launcher to run app ? 
I will back to that tomorrow with more fresh mind.

**Comment by joshtynjala** [comment]
I think that `o` is an alias for the `output` compiler option.

**Comment by piotrzarzycki21** [comment]
@joshtynjala I cannot figure out what is happening. What actually language server have to get in order to launch air project ? 

Second question is - What process of language server is responsible for running app ?

**Comment by joshtynjala** [comment]
The language server does not run the app. It doesn't build the app either. The language server only provides code intelligence. asconfigc builds the app, and it is not really part of the language server. The SWF debug adapter runs the app. If you switch from building with mxmlc directly to building with asconfigc, you shouldn't need to change anything about how the app is run/launched. Your issue sounds like something is going wrong in the build step.

As I suggested in a previous post, you should compare the options that Moonshine passes to mxmlc with the options that asconfigc passes to mxmlc. You can see the exact options used by asconfigc by passing the --verbose option to it.

**Comment by rat-moonshine** [comment]
@piotrzarzycki21 you can check through [SWFLauncherPlugin](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/swflauncher/SWFLauncherPlugin.as) on AIR launch procedure, which Josh suggested. Different project types may require you to add separate properties, i.e. mobile.
