### ISSUE TITLE
Notification Error on MoonshineSharedCore Project

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#320]
@joshtynjala:  With the latest build from Bamboo on Windows, I get these errors when opening the MoonshineSharedCore project:

    : Failed to get compile settings for +configname=flex.
    : 
    : Jun 29, 2018 11:15:44 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleNotification
    : WARNING: Notification threw an exception: {
    :   "jsonrpc": "2.0",
    :   "method": "moonshine/didChangeProjectConfiguration",
    :   "params": {
    :     "files": [
    :       "C:\\Flex\\workspace\\Moonshine-IDE\\ide\\MoonshineSharedCore\\src\\MoonshineSharedCore.as"
    :     ],
    :     "compilerOptions": {
    :       "source-path": [
    :         "C:\\Flex\\workspace\\Moonshine-IDE\\ide\\MoonshineSharedCore\\src"
    :       ]
    :     },
    :     "type": "lib",
    :     "additionalOptions": " -define+\u003dCONFIG::OSX,false -locale\u003den_US,ja_JP",
    :     "config": "flex"
    :   }
    : }
    : java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    : 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:63)
    : 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:148)
    : 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:216)
    : 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:183)
    : 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:188)
    : 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:90)
    : 	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:95)
    : 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    : 	at java.lang.Thread.run(Thread.java:748)
    : Caused by: java.lang.reflect.InvocationTargetException
    : 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    : 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    : 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    : 	at java.lang.reflect.Method.invoke(Method.java:498)
    : 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:61)
    : 	... 11 more
    : Caused by: java.lang.NullPointerException
    : 	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.prepareNewProject(ActionScriptTextDocumentService.java:1612)
    : 	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.refreshProjectOptions(ActionScriptTextDocumentService.java:1661)
    : 	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.checkProjectForProblems(ActionScriptTextDocumentService.java:5164)
    : 	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.checkForProblemsNow(ActionScriptTextDocumentService.java:1475)
    : 	at moonshine.MoonshineLanguageServer.didChangeProjectConfiguration(MoonshineLanguageServer.java:28)
    : 	... 16 more

This triggers consistently with MoonshineSharedCore both when opening the project and restarting Moonshine with the project open.  I got the same error with both the "master" and "Test_Devsena" branches.

This does not trigger for MoonshineDESKTOPevolved.

I got this error while trying to test #315.  The first error message seems to be from #221, but I haven't seen the other error before.

**Comment by joshtynjala** [comment]
I'll take a look at this one early next week.

**Comment by joshtynjala** [comment]
This error has been fixed.

**Comment by piotrzarzycki21** [comment]
@joshtynjala I'm having following exception. It's a bit similar what Joel observed. I have the freshest sources. Once it happen code completion is become unstable. I have to restart Moonshine.

```
Exception in thread "Thread-165" 
: java.lang.NullPointerException
: 	at org.apache.royale.compiler.internal.units.CompilationUnitBase.getSyntaxTreeRequest(CompilationUnitBase.java:611)
: 	at org.apache.royale.compiler.internal.units.InvisibleCompilationUnit.getSyntaxTreeRequest(InvisibleCompilationUnit.java:78)
: 	at com.nextgenactionscript.vscode.utils.RealTimeProblemAnalyzer.run(RealTimeProblemAnalyzer.java:124)
: 	at java.lang.Thread.run(Thread.java:748)
: Jul 04, 2018 11:33:49 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleNotification
: WARNING: Notification threw an exception: {
:   "jsonrpc": "2.0",
:   "method": "textDocument/didChange",
:   "params": {
:     "textDocument": {
:       "version": 171,
:       "uri": "file:///D:/Work/projects/Prominic.NET/MoonshineTests/FilesRemovingTest/src/FilesRemovingTest.mxml"
:     },
:     "contentChanges": [
:       {
:         "rangeLength": 0,
:         "text": "\u003c?xml version\u003d\"1.0\" encoding\u003d\"utf-8\"?\u003e\n\u003cs:WindowedApplication xmlns:fx\u003d\"http://ns.adobe.com/mxml/2009\" \n\t\t\t\t\t   xmlns:s\u003d\"library://ns.adobe.com/flex/spark\" \n\t\t\t\t\t   xmlns:mx\u003d\"library://ns.adobe.com/flex/mx\" minWidth\u003d\"955\" minHeight\u003d\"600\"\u003e\n\n\t\u003cfx:Script\u003e\n\t\t\u003c![CDATA[\n\t\t\timport flash.events.MouseEvent;\n\t\t\timport flash.filesystem.File;\n\t\t\t\n\t\t\tprivate var _file:F\n\t\t\tprivate function onOpenFolderClick(event:MouseEvent):void\n\t\t\t{\n\t\t\t\tvar file:File \u003d new File(); \n\t\t\t\tfile.addEventListener(Event.SELECT, dirSelected); \n\t\t\t\tfile.browseForDirectory(\"Select a directory\"); \n\t\t\t}\n\t\t]]\u003e\n\t\u003c/fx:Script\u003e\n\t\u003cs:Button label\u003d\"Open Folder\" click\u003d\"onOpenFolderClick(event)\"/\u003e\n\u003c/s:WindowedApplication\u003e"
:       }
:     ]
:   }
: }
: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
: 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:63)
: 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:148)
: 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:216)
: 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:183)
: 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:188)
: 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:90)
: 	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:95)
: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
: 	at java.lang.Thread.run(Thread.java:748)
: Caused by: java.lang.reflect.InvocationTargetException
: 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
: 	at java.lang.reflect.Method.invoke(Method.java:498)
: 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:61)
: 	... 11 more
: Caused by: java.lang.NullPointerException
: 	at org.apache.royale.compiler.internal.units.CompilationUnitBase.getSyntaxTreeRequest(CompilationUnitBase.java:611)
: 	at org.apache.royale.compiler.internal.units.InvisibleCompilationUnit.getSyntaxTreeRequest(InvisibleCompilationUnit.java:78)
: 	at com.nextgenactionscript.vscode.utils.RealTimeProblemAnalyzer.completePendingRequests(RealTimeProblemAnalyzer.java:164)
: 	at com.nextgenactionscript.vscode.utils.RealTimeProblemAnalyzer.setCompilationUnit(RealTimeProblemAnalyzer.java:99)
: 	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.didChange(ActionScriptTextDocumentService.java:1288)
: 	... 15 more
: 
: Jul 04, 2018 11:33:49 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleNotification
: WARNING: Notification threw an exception: {
:   "jsonrpc": "2.0",
:   "method": "textDocument/didChange",
:   "params": {
:     "textDocument": {
:       "version": 172,
:       "uri": "file:///D:/Work/projects/Prominic.NET/MoonshineTests/FilesRemovingTest/src/FilesRemovingTest.mxml"
:     },
:     "contentChanges": [
:       {
:         "rangeLength": 0,
:         "text": "\u003c?xml version\u003d\"1.0\" encoding\u003d\"utf-8\"?\u003e\n\u003cs:WindowedApplication xmlns:fx\u003d\"http://ns.adobe.com/mxml/2009\" \n\t\t\t\t\t   xmlns:s\u003d\"library://ns.adobe.com/flex/spark\" \n\t\t\t\t\t   xmlns:mx\u003d\"library://ns.adobe.com/flex/mx\" minWidth\u003d\"955\" minHeight\u003d\"600\"\u003e\n\n\t\u003cfx:Script\u003e\n\t\t\u003c![CDATA[\n\t\t\timport flash.events.MouseEvent;\n\t\t\timport flash.filesystem.File;\n\t\t\t\n\t\t\tprivate var _file:Fi\n\t\t\tprivate function onOpenFolderClick(event:MouseEvent):void\n\t\t\t{\n\t\t\t\tvar file:File \u003d new File(); \n\t\t\t\tfile.addEventListener(Event.SELECT, dirSelected); \n\t\t\t\tfile.browseForDirectory(\"Select a directory\"); \n\t\t\t}\n\t\t]]\u003e\n\t\u003c/fx:Script\u003e\n\t\u003cs:Button label\u003d\"Open Folder\" click\u003d\"onOpenFolderClick(event)\"/\u003e\n\u003c/s:WindowedApplication\u003e"
:       }
:     ]
:   }
: }
: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
: 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:63)
: 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:148)
: 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:216)
: 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:183)
: 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:188)
: 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:90)
: 	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:95)
: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
: 	at java.lang.Thread.run(Thread.java:748)
: Caused by: java.lang.reflect.InvocationTargetException
: 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
: 	at java.lang.reflect.Method.invoke(Method.java:498)
: 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:61)
: 	... 11 more
: Caused by: java.lang.NullPointerException
: 	at org.apache.royale.compiler.internal.units.CompilationUnitBase.getSyntaxTreeRequest(CompilationUnitBase.java:611)
: 	at org.apache.royale.compiler.internal.units.InvisibleCompilationUnit.getSyntaxTreeRequest(InvisibleCompilationUnit.java:78)
: 	at com.nextgenactionscript.vscode.utils.RealTimeProblemAnalyzer.completePendingRequests(RealTimeProblemAnalyzer.java:164)
: 	at com.nextgenactionscript.vscode.utils.RealTimeProblemAnalyzer.setCompilationUnit(RealTimeProblemAnalyzer.java:99)
: 	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.didChange(ActionScriptTextDocumentService.java:1288)
: 	... 15 more
: 
: Jul 04, 2018 11:33:50 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleNotification
: WARNING: Notification threw an exception: {
:   "jsonrpc": "2.0",
:   "method": "textDocument/didChange",
:   "params": {
:     "textDocument": {
:       "version": 173,
:       "uri": "file:///D:/Work/projects/Prominic.NET/MoonshineTests/FilesRemovingTest/src/FilesRemovingTest.mxml"
:     },
:     "contentChanges": [
:       {
:         "rangeLength": 0,
:         "text": "\u003c?xml version\u003d\"1.0\" encoding\u003d\"utf-8\"?\u003e\n\u003cs:WindowedApplication xmlns:fx\u003d\"http://ns.adobe.com/mxml/2009\" \n\t\t\t\t\t   xmlns:s\u003d\"library://ns.adobe.com/flex/spark\" \n\t\t\t\t\t   xmlns:mx\u003d\"library://ns.adobe.com/flex/mx\" minWidth\u003d\"955\" minHeight\u003d\"600\"\u003e\n\n\t\u003cfx:Script\u003e\n\t\t\u003c![CDATA[\n\t\t\timport flash.events.MouseEvent;\n\t\t\timport flash.filesystem.File;\n\t\t\t\n\t\t\tprivate var _file:Fil\n\t\t\tprivate function onOpenFolderClick(event:MouseEvent):void\n\t\t\t{\n\t\t\t\tvar file:File \u003d new File(); \n\t\t\t\tfile.addEventListener(Event.SELECT, dirSelected); \n\t\t\t\tfile.browseForDirectory(\"Select a directory\"); \n\t\t\t}\n\t\t]]\u003e\n\t\u003c/fx:Script\u003e\n\t\u003cs:Button label\u003d\"Open Folder\" click\u003d\"onOpenFolderClick(event)\"/\u003e\n\u003c/s:WindowedApplication\u003e"
:       }
:     ]
:   }
: }
: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
: 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:63)
: 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:148)
: 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:216)
: 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:183)
: 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:188)
: 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:90)
: 	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:95)
: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
: 	at java.lang.Thread.run(Thread.java:748)
: Caused by: java.lang.reflect.InvocationTargetException
: 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
: 	at java.lang.reflect.Method.invoke(Method.java:498)
: 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:61)
: 	... 11 more
: Caused by: java.lang.NullPointerException
: 	at org.apache.royale.compiler.internal.units.CompilationUnitBase.getSyntaxTreeRequest(CompilationUnitBase.java:611)
: 	at org.apache.royale.compiler.internal.units.InvisibleCompilationUnit.getSyntaxTreeRequest(InvisibleCompilationUnit.java:78)
: 	at com.nextgenactionscript.vscode.utils.RealTimeProblemAnalyzer.completePendingRequests(RealTimeProblemAnalyzer.java:164)
: 	at com.nextgenactionscript.vscode.utils.RealTimeProblemAnalyzer.setCompilationUnit(RealTimeProblemAnalyzer.java:99)
: 	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.didChange(ActionScriptTextDocumentService.java:1288)
: 	... 15 more
: 
: Jul 04, 2018 11:33:50 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleNotification
: WARNING: Notification threw an exception: {
:   "jsonrpc": "2.0",
:   "method": "textDocument/didChange",
:   "params": {
:     "textDocument": {
:       "version": 174,
:       "uri": "file:///D:/Work/projects/Prominic.NET/MoonshineTests/FilesRemovingTest/src/FilesRemovingTest.mxml"
:     },
:     "contentChanges": [
:       {
:         "rangeLength": 0,
:         "text": "\u003c?xml version\u003d\"1.0\" encoding\u003d\"utf-8\"?\u003e\n\u003cs:WindowedApplication xmlns:fx\u003d\"http://ns.adobe.com/mxml/2009\" \n\t\t\t\t\t   xmlns:s\u003d\"library://ns.adobe.com/flex/spark\" \n\t\t\t\t\t   xmlns:mx\u003d\"library://ns.adobe.com/flex/mx\" minWidth\u003d\"955\" minHeight\u003d\"600\"\u003e\n\n\t\u003cfx:Script\u003e\n\t\t\u003c![CDATA[\n\t\t\timport flash.events.MouseEvent;\n\t\t\timport flash.filesystem.File;\n\t\t\t\n\t\t\tprivate var _file:File\n\t\t\tprivate function onOpenFolderClick(event:MouseEvent):void\n\t\t\t{\n\t\t\t\tvar file:File \u003d new File(); \n\t\t\t\tfile.addEventListener(Event.SELECT, dirSelected); \n\t\t\t\tfile.browseForDirectory(\"Select a directory\"); \n\t\t\t}\n\t\t]]\u003e\n\t\u003c/fx:Script\u003e\n\t\u003cs:Button label\u003d\"Open Folder\" click\u003d\"onOpenFolderClick(event)\"/\u003e\n\u003c/s:WindowedApplication\u003e"
:       }
:     ]
:   }
: }
: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
: 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:63)
: 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:148)
: 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:216)
: 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:183)
: 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:188)
: 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:90)
: 	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:95)
: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
: 	at java.lang.Thread.run(Thread.java:748)
: Caused by: java.lang.reflect.InvocationTargetException
: 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
: 	at java.lang.reflect.Method.invoke(Method.java:498)
: 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:61)
: 	... 11 more
: Caused by: java.lang.NullPointerException
: 	at org.apache.royale.compiler.internal.units.CompilationUnitBase.getSyntaxTreeRequest(CompilationUnitBase.java:611)
: 	at org.apache.royale.compiler.internal.units.InvisibleCompilationUnit.getSyntaxTreeRequest(InvisibleCompilationUnit.java:78)
: 	at com.nextgenactionscript.vscode.utils.RealTimeProblemAnalyzer.completePendingRequests(RealTimeProblemAnalyzer.java:164)
: 	at com.nextgenactionscript.vscode.utils.RealTimeProblemAnalyzer.setCompilationUnit(RealTimeProblemAnalyzer.java:99)
: 	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.didChange(ActionScriptTextDocumentService.java:1288)
: 	... 15 more
```

**Comment by joshtynjala** [comment]
Hmmm... As you can see, it's an null reference exception in the Royale compiler:

> at org.apache.royale.compiler.internal.units.CompilationUnitBase.getSyntaxTreeRequest(CompilationUnitBase.java:611)

I'll investigate, but there's a chance that I won't be able to do anything.

@piotrzarzycki21 I assume that you're reproducing this in the MoonshineSharedCore project or at least another library project? If not, can you open a separate issue because this is not related to the original issue.

**Comment by piotrzarzycki21** [comment]
@joshtynjala but it was Adobe Air Desktop Flex project. The only thing Royale related was that I had in the main Moonshine Settings setup newest nightly build of Royale in SDK. Project itself had in the settings Flex SDK with Adobe Air 30.

**Comment by piotrzarzycki21** [comment]
Got it! I will raise separate issue tomorrow my time.

**Comment by piotrzarzycki21** [comment]
Just raised an issue #323
