### ISSUE TITLE
Null pointer exception - method textDocument/didChange

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#323]
In the following project [FilesRemovingTest.zip](https://github.com/prominic/Moonshine-IDE/files/2162871/FilesRemovingTest.zip) I was getting exception:

```
Exception in thread "Thread-165" 
: java.lang.NullPointerException
: 	at org.apache.royale.compiler.internal.units.CompilationUnitBase.getSyntaxTreeRequest(CompilationUnitBase.java:611)
: 	at org.apache.royale.compiler.internal.units.InvisibleCompilationUnit.getSyntaxTreeRequest(InvisibleCompilationUnit.java:78)
: 	at com.nextgenactionscript.vscode.utils.RealTimeProblemAnalyzer.run(RealTimeProblemAnalyzer.java:124)
: 	at java.lang.Thread.run(Thread.java:748)
: Jul 04, 2018 11:33:49 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleNotification
: WARNING: Notification threw an exception: {
:   "jsonrpc": "2.0",
:   "method": "textDocument/didChange",
:   "params": {
:     "textDocument": {
:       "version": 171,
:       "uri": "file:///D:/Work/projects/Prominic.NET/MoonshineTests/FilesRemovingTest/src/FilesRemovingTest.mxml"
:     },
:     "contentChanges": [
:       {
:         "rangeLength": 0,
:         "text": "\u003c?xml version\u003d\"1.0\" encoding\u003d\"utf-8\"?\u003e\n\u003cs:WindowedApplication xmlns:fx\u003d\"http://ns.adobe.com/mxml/2009\" \n\t\t\t\t\t   xmlns:s\u003d\"library://ns.adobe.com/flex/spark\" \n\t\t\t\t\t   xmlns:mx\u003d\"library://ns.adobe.com/flex/mx\" minWidth\u003d\"955\" minHeight\u003d\"600\"\u003e\n\n\t\u003cfx:Script\u003e\n\t\t\u003c![CDATA[\n\t\t\timport flash.events.MouseEvent;\n\t\t\timport flash.filesystem.File;\n\t\t\t\n\t\t\tprivate var _file:F\n\t\t\tprivate function onOpenFolderClick(event:MouseEvent):void\n\t\t\t{\n\t\t\t\tvar file:File \u003d new File(); \n\t\t\t\tfile.addEventListener(Event.SELECT, dirSelected); \n\t\t\t\tfile.browseForDirectory(\"Select a directory\"); \n\t\t\t}\n\t\t]]\u003e\n\t\u003c/fx:Script\u003e\n\t\u003cs:Button label\u003d\"Open Folder\" click\u003d\"onOpenFolderClick(event)\"/\u003e\n\u003c/s:WindowedApplication\u003e"
:       }
:     ]
:   }
: }
: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
: 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:63)
: 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:148)
: 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:216)
: 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:183)
: 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:188)
: 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:90)
: 	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:95)
: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
: 	at java.lang.Thread.run(Thread.java:748)
: Caused by: java.lang.reflect.InvocationTargetException
: 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
: 	at java.lang.reflect.Method.invoke(Method.java:498)
: 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:61)
: 	... 11 more
: Caused by: java.lang.NullPointerException
: 	at org.apache.royale.compiler.internal.units.CompilationUnitBase.getSyntaxTreeRequest(CompilationUnitBase.java:611)
: 	at org.apache.royale.compiler.internal.units.InvisibleCompilationUnit.getSyntaxTreeRequest(InvisibleCompilationUnit.java:78)
: 	at com.nextgenactionscript.vscode.utils.RealTimeProblemAnalyzer.completePendingRequests(RealTimeProblemAnalyzer.java:164)
: 	at com.nextgenactionscript.vscode.utils.RealTimeProblemAnalyzer.setCompilationUnit(RealTimeProblemAnalyzer.java:99)
: 	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.didChange(ActionScriptTextDocumentService.java:1288)
: 	... 15 more
: 
: Jul 04, 2018 11:33:49 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleNotification
: WARNING: Notification threw an exception: {
:   "jsonrpc": "2.0",
:   "method": "textDocument/didChange",
:   "params": {
:     "textDocument": {
:       "version": 172,
:       "uri": "file:///D:/Work/projects/Prominic.NET/MoonshineTests/FilesRemovingTest/src/FilesRemovingTest.mxml"
:     },
:     "contentChanges": [
:       {
:         "rangeLength": 0,
:         "text": "\u003c?xml version\u003d\"1.0\" encoding\u003d\"utf-8\"?\u003e\n\u003cs:WindowedApplication xmlns:fx\u003d\"http://ns.adobe.com/mxml/2009\" \n\t\t\t\t\t   xmlns:s\u003d\"library://ns.adobe.com/flex/spark\" \n\t\t\t\t\t   xmlns:mx\u003d\"library://ns.adobe.com/flex/mx\" minWidth\u003d\"955\" minHeight\u003d\"600\"\u003e\n\n\t\u003cfx:Script\u003e\n\t\t\u003c![CDATA[\n\t\t\timport flash.events.MouseEvent;\n\t\t\timport flash.filesystem.File;\n\t\t\t\n\t\t\tprivate var _file:Fi\n\t\t\tprivate function onOpenFolderClick(event:MouseEvent):void\n\t\t\t{\n\t\t\t\tvar file:File \u003d new File(); \n\t\t\t\tfile.addEventListener(Event.SELECT, dirSelected); \n\t\t\t\tfile.browseForDirectory(\"Select a directory\"); \n\t\t\t}\n\t\t]]\u003e\n\t\u003c/fx:Script\u003e\n\t\u003cs:Button label\u003d\"Open Folder\" click\u003d\"onOpenFolderClick(event)\"/\u003e\n\u003c/s:WindowedApplication\u003e"
:       }
:     ]
:   }
: }
: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
: 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:63)
: 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:148)
: 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:216)
: 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:183)
: 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:188)
: 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:90)
: 	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:95)
: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
: 	at java.lang.Thread.run(Thread.java:748)
: Caused by: java.lang.reflect.InvocationTargetException
: 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
: 	at java.lang.reflect.Method.invoke(Method.java:498)
: 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:61)
: 	... 11 more
: Caused by: java.lang.NullPointerException
: 	at org.apache.royale.compiler.internal.units.CompilationUnitBase.getSyntaxTreeRequest(CompilationUnitBase.java:611)
: 	at org.apache.royale.compiler.internal.units.InvisibleCompilationUnit.getSyntaxTreeRequest(InvisibleCompilationUnit.java:78)
: 	at com.nextgenactionscript.vscode.utils.RealTimeProblemAnalyzer.completePendingRequests(RealTimeProblemAnalyzer.java:164)
: 	at com.nextgenactionscript.vscode.utils.RealTimeProblemAnalyzer.setCompilationUnit(RealTimeProblemAnalyzer.java:99)
: 	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.didChange(ActionScriptTextDocumentService.java:1288)
: 	... 15 more
: 
: Jul 04, 2018 11:33:50 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleNotification
: WARNING: Notification threw an exception: {
:   "jsonrpc": "2.0",
:   "method": "textDocument/didChange",
:   "params": {
:     "textDocument": {
:       "version": 173,
:       "uri": "file:///D:/Work/projects/Prominic.NET/MoonshineTests/FilesRemovingTest/src/FilesRemovingTest.mxml"
:     },
:     "contentChanges": [
:       {
:         "rangeLength": 0,
:         "text": "\u003c?xml version\u003d\"1.0\" encoding\u003d\"utf-8\"?\u003e\n\u003cs:WindowedApplication xmlns:fx\u003d\"http://ns.adobe.com/mxml/2009\" \n\t\t\t\t\t   xmlns:s\u003d\"library://ns.adobe.com/flex/spark\" \n\t\t\t\t\t   xmlns:mx\u003d\"library://ns.adobe.com/flex/mx\" minWidth\u003d\"955\" minHeight\u003d\"600\"\u003e\n\n\t\u003cfx:Script\u003e\n\t\t\u003c![CDATA[\n\t\t\timport flash.events.MouseEvent;\n\t\t\timport flash.filesystem.File;\n\t\t\t\n\t\t\tprivate var _file:Fil\n\t\t\tprivate function onOpenFolderClick(event:MouseEvent):void\n\t\t\t{\n\t\t\t\tvar file:File \u003d new File(); \n\t\t\t\tfile.addEventListener(Event.SELECT, dirSelected); \n\t\t\t\tfile.browseForDirectory(\"Select a directory\"); \n\t\t\t}\n\t\t]]\u003e\n\t\u003c/fx:Script\u003e\n\t\u003cs:Button label\u003d\"Open Folder\" click\u003d\"onOpenFolderClick(event)\"/\u003e\n\u003c/s:WindowedApplication\u003e"
:       }
:     ]
:   }
: }
: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
: 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:63)
: 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:148)
: 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:216)
: 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:183)
: 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:188)
: 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:90)
: 	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:95)
: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
: 	at java.lang.Thread.run(Thread.java:748)
: Caused by: java.lang.reflect.InvocationTargetException
: 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
: 	at java.lang.reflect.Method.invoke(Method.java:498)
: 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:61)
: 	... 11 more
: Caused by: java.lang.NullPointerException
: 	at org.apache.royale.compiler.internal.units.CompilationUnitBase.getSyntaxTreeRequest(CompilationUnitBase.java:611)
: 	at org.apache.royale.compiler.internal.units.InvisibleCompilationUnit.getSyntaxTreeRequest(InvisibleCompilationUnit.java:78)
: 	at com.nextgenactionscript.vscode.utils.RealTimeProblemAnalyzer.completePendingRequests(RealTimeProblemAnalyzer.java:164)
: 	at com.nextgenactionscript.vscode.utils.RealTimeProblemAnalyzer.setCompilationUnit(RealTimeProblemAnalyzer.java:99)
: 	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.didChange(ActionScriptTextDocumentService.java:1288)
: 	... 15 more
: 
: Jul 04, 2018 11:33:50 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleNotification
: WARNING: Notification threw an exception: {
:   "jsonrpc": "2.0",
:   "method": "textDocument/didChange",
:   "params": {
:     "textDocument": {
:       "version": 174,
:       "uri": "file:///D:/Work/projects/Prominic.NET/MoonshineTests/FilesRemovingTest/src/FilesRemovingTest.mxml"
:     },
:     "contentChanges": [
:       {
:         "rangeLength": 0,
:         "text": "\u003c?xml version\u003d\"1.0\" encoding\u003d\"utf-8\"?\u003e\n\u003cs:WindowedApplication xmlns:fx\u003d\"http://ns.adobe.com/mxml/2009\" \n\t\t\t\t\t   xmlns:s\u003d\"library://ns.adobe.com/flex/spark\" \n\t\t\t\t\t   xmlns:mx\u003d\"library://ns.adobe.com/flex/mx\" minWidth\u003d\"955\" minHeight\u003d\"600\"\u003e\n\n\t\u003cfx:Script\u003e\n\t\t\u003c![CDATA[\n\t\t\timport flash.events.MouseEvent;\n\t\t\timport flash.filesystem.File;\n\t\t\t\n\t\t\tprivate var _file:File\n\t\t\tprivate function onOpenFolderClick(event:MouseEvent):void\n\t\t\t{\n\t\t\t\tvar file:File \u003d new File(); \n\t\t\t\tfile.addEventListener(Event.SELECT, dirSelected); \n\t\t\t\tfile.browseForDirectory(\"Select a directory\"); \n\t\t\t}\n\t\t]]\u003e\n\t\u003c/fx:Script\u003e\n\t\u003cs:Button label\u003d\"Open Folder\" click\u003d\"onOpenFolderClick(event)\"/\u003e\n\u003c/s:WindowedApplication\u003e"
:       }
:     ]
:   }
: }
: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
: 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:63)
: 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:148)
: 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:216)
: 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:183)
: 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:188)
: 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:90)
: 	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:95)
: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
: 	at java.lang.Thread.run(Thread.java:748)
: Caused by: java.lang.reflect.InvocationTargetException
: 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
: 	at java.lang.reflect.Method.invoke(Method.java:498)
: 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:61)
: 	... 11 more
: Caused by: java.lang.NullPointerException
: 	at org.apache.royale.compiler.internal.units.CompilationUnitBase.getSyntaxTreeRequest(CompilationUnitBase.java:611)
: 	at org.apache.royale.compiler.internal.units.InvisibleCompilationUnit.getSyntaxTreeRequest(InvisibleCompilationUnit.java:78)
: 	at com.nextgenactionscript.vscode.utils.RealTimeProblemAnalyzer.completePendingRequests(RealTimeProblemAnalyzer.java:164)
: 	at com.nextgenactionscript.vscode.utils.RealTimeProblemAnalyzer.setCompilationUnit(RealTimeProblemAnalyzer.java:99)
: 	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.didChange(ActionScriptTextDocumentService.java:1288)
: 	... 15 more
```

Extracted from #320.

**Comment by piotrzarzycki21** [comment]
This error is most annoying right now. I'm getting it after couple of minutes of usage Moonshine and have to restart IDE. :( I have installed version with your yesterdays changes.

**Comment by joshtynjala** [comment]
I'll make this my priority next week.

**Comment by piotrzarzycki21** [comment]
@joshtynjala I just tested it and didn't notice anymore that issue. Thanks!
