### ISSUE TITLE
Exception during waitForBuildFinish(): java.lang.NullPointerException

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#338]
I got that exception when I was deleting something from the editor. It happened with fresh sources from git.

```
: Exception during waitForBuildFinish(): java.lang.NullPointerException
: java.lang.NullPointerException
: 	at org.apache.royale.compiler.internal.units.CompilationUnitBase.getABCBytesRequest(CompilationUnitBase.java:623)
: 	at org.apache.royale.compiler.internal.units.CompilationUnitBase.waitForBuildFinish(CompilationUnitBase.java:1059)
: 	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.checkCompilationUnitForAllProblems(ActionScriptTextDocumentService.java:5353)
: 
: 	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.checkFilePathForAllProblems(ActionScriptTextDocumentService.java:5310)
: 	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.checkFilePathForProblems(ActionScriptTextDocumentService.java:5236)
: 	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.checkProjectForProblems(ActionScriptTextDocumentService.java:5220)
: 	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService.access$500(ActionScriptTextDocumentService.java:251)
: 	at com.nextgenactionscript.vscode.ActionScriptTextDocumentService$3.run(ActionScriptTextDocumentService.java:1609)
: Exception in compiler while checking for problems: java.lang.NullPointerException
: java.lang.NullPointerException
: 	at org.apache.royale.compiler.internal.units.CompilationUnitBase.getSyntaxTreeRequest(CompilationUnitBase.java:611)
: 	at org.apache.royale.compiler.internal.units.InvisibleCompilationUnit.getSyntaxTreeRequest(InvisibleCompilationUnit.java:78)
: 	at com.nextgenactionscript.vscode.utils.RealTimeProblemAnalyzer.publishDiagnostics(RealTimeProblemAnalyzer.java:197)
: 	at com.nextgenactionscript.vscode.utils.RealTimeProblemAnalyzer.run(RealTimeProblemAnalyzer.java:142)
: 	at java.lang.Thread.run(Thread.java:748)
: Exception in thread "Thread-18" java.lang.NullPointerException
: 	at com.nextgenactionscript.vscode.utils.RealTimeProblemAnalyzer.publishDiagnostics(RealTimeProblemAnalyzer.java:216)
: 	at com.nextgenactionscript.vscode.utils.RealTimeProblemAnalyzer.run(RealTimeProblemAnalyzer.java:142)
: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by joshtynjala** [comment]
I have updated to vscode-nextgenas v0.14.0 in commit 614e93cd80d42fd5138ce2ddcb3a4c2995f87ad3, and this should be resolved.
