### ISSUE TITLE
Cannot run Flex application in debug mode -> Could not find or load main class com.nextgenactionscript.vscode.SWFDebug

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#388]
I have simple Desktop Flex app and when I'm trying to run it by menu **Debug** -> **Build & Debug** I'm getting following error.

```
Compiling FlexDesktopProject
: Sending to mxmlc: mxmlc -load-config+=obj/FlexDesktopProjectConfig.xml -optimize=false +configname=air -debug=true -o bin-debug/FlexDesktopProject.swf
: Apache Flex Compiler SHell (fcsh)
: Version 4.16.1 build 20171115
: Copyright 2017 The Apache Software Foundation.
: 
: (fcsh) 
: FSCH target: 1
: fcsh: Assigned 1 as the compile target id
: Loading configuration file D:\Work\flex-sdk-4.16.1_adobe_ari_31\frameworks\air-config.xml
: Loading configuration file D:\Work\projects\Prominic.NET\Moonshine Tests\Flex Projects\FlexDesktopProject\obj\FlexDesktopProjectConfig.xml
: bin-debug/FlexDesktopProject.swf (1005895 bytes)
: (fcsh) 
: Project Build Successfully.
: Process error: Error: Could not find or load main class com.nextgenactionscript.vscode.SWFDebug
: Process error: Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
```

**Comment by piotrzarzycki21** [comment]
During second attempt of Build & Debug I got following one:

```
: Compiling FlexDesktopProject
: Sending to mxmlc: mxmlc -load-config+=obj/FlexDesktopProjectConfig.xml -optimize=false +configname=air -debug=true -o bin-debug/FlexDesktopProject.swf
: Apache Flex Compiler SHell (fcsh)
: Version 4.16.1 build 20171115
: Copyright 2017 The Apache Software Foundation.
: 
: (fcsh) 
: FSCH target: 1
: fcsh: Assigned 1 as the compile target id
: Loading configuration file D:\Work\flex-sdk-4.16.1_adobe_ari_31\frameworks\air-config.xml
: Loading configuration file D:\Work\projects\Prominic.NET\Moonshine Tests\Flex Projects\FlexDesktopProject\obj\FlexDesktopProjectConfig.xml
: Sep 26, 2018 11:52:03 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
: SEVERE: Internal error: java.util.ConcurrentModificationException
: java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
: 	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
: 	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
: 	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
: 	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
: 	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
: 	at java.lang.Thread.run(Thread.java:748)
: Caused by: java.util.ConcurrentModificationException
: 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442)
: 	at java.util.HashMap$KeyIterator.next(HashMap.java:1466)
: 	at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1042)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.findCompilationUnit(ActionScriptTextDocumentService.java:5618)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.findCompilationUnit(ActionScriptTextDocumentService.java:5639)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.getCompilationUnit(ActionScriptTextDocumentService.java:5735)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.getOffsetMXMLTag(ActionScriptTextDocumentService.java:6204)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.getOffsetMXMLTag(ActionScriptTextDocumentService.java:6174)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.lambda$hover$1(ActionScriptTextDocumentService.java:511)
: 	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
: 	... 5 more
: 
: Sep 26, 2018 11:52:04 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
: SEVERE: Internal error: java.util.ConcurrentModificationException
: java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
: 	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
: 	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
: 	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
: 	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
: 	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
: 	at java.lang.Thread.run(Thread.java:748)
: Caused by: java.util.ConcurrentModificationException
: 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442)
: 	at java.util.HashMap$KeyIterator.next(HashMap.java:1466)
: 	at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1042)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.findCompilationUnit(ActionScriptTextDocumentService.java:5618)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.findCompilationUnit(ActionScriptTextDocumentService.java:5639)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.getCompilationUnit(ActionScriptTextDocumentService.java:5735)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.getOffsetMXMLTag(ActionScriptTextDocumentService.java:6204)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.getOffsetMXMLTag(ActionScriptTextDocumentService.java:6174)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.lambda$hover$1(ActionScriptTextDocumentService.java:511)
: 	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
: 	... 5 more
: 
: bin-debug/FlexDesktopProject.swf (1014276 bytes)
: (fcsh) 
: Project Build Successfully.
: Process error: Error: Could not find or load main class com.nextgenactionscript.vscode.SWFDebug
: Process error: Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
```

**Comment by joshtynjala** [comment]
In vscode-nextgenas v0.14, I updated the package names to `com.as3mxml`. When I updated *swf-debugger.jar* in Moonshine, I forgot to change the launch command to use the new package name.

**Comment by atinprominic** [comment]
@piotrzarzycki21 I tested and found that there are still some errors while I do Debug. Please find below error logs:


: Compiling Test388_1
: Sending to mxmlc: mxmlc -load-config+=obj/Test388_1Config.xml -optimize=false +configname=air -debug=true -o bin-debug/Test388_1.swf
: FSCH target: 1
: Apache Flex Compiler SHell (fcsh)
: Version 4.16.0 build 20170305
: Copyright 2017 The Apache Software Foundation.
: (fcsh) fcsh: Assigned 1 as the compile target id
: Loading configuration file /Users/atin/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.0_AIR_25.0/frameworks/air-config.xml
: Loading configuration file /Users/atin/Documents/MoonshineProjects/Test388_1/obj/Test388_1Config.xml
: bin-debug/Test388_1.swf (1007403 bytes)
: (fcsh) 
: Project Build Successfully.
: Error #1009
: TypeError: Error #1009
: 	at actionScripts.plugins.vscodeDebug::VSCodeDebugProtocolPlugin/dispatcher_postBuildHandler()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at actionScripts.plugins.as3project.mxmlc::MXMLCPlugin/launchDebuggingAfterBuild()
: 	at actionScripts.plugins.as3project.mxmlc::MXMLCPlugin/shellData()
:
: Click here to Report a Bug


Also I recorded the screen for reference.
![388-test](https://user-images.githubusercontent.com/34882311/46398169-00b4fc80-c712-11e8-8190-fd9e88550539.gif)
∂

**Comment by joshtynjala** [comment]
@piotrzarzycki21 @atinprominic Unfortunately, I cannot reproduce this error. When I try to debug a Flex desktop project, it launches and connects to the debugger correctly.

Since there are no line numbers in the stack trace, I can't even guess what object might be null in dispatcher_postBuildHandler().
