### ISSUE TITLE
Java Gradle project throwing IllegalArgumentException with Open JDK 11.0.2

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#466]
In following scenario I'm getting exception for Java Gradle project:

**Scenario 1:**
1. Create Java Gradle project using newest [development build](https://moonshine-ide.com/downloads/releases/dev/windows/)

**Results:**
```
: Could not determine java version from '11.0.2'.
: java.lang.IllegalArgumentException: Could not determine java version from '11.0.2'.
: 	at org.gradle.api.JavaVersion.toVersion(JavaVersion.java:72)
: 	at org.gradle.api.JavaVersion.current(JavaVersion.java:82)
: 	at org.gradle.internal.jvm.UnsupportedJavaRuntimeException.javaDeprecationWarning(UnsupportedJavaRuntimeException.java:36)
: 	at org.gradle.tooling.internal.consumer.ConnectorServices.checkJavaVersion(ConnectorServices.java:59)
: 	at org.gradle.tooling.internal.consumer.ConnectorServices.createCancellationTokenSource(ConnectorServices.java:41)
: 	at org.gradle.tooling.GradleConnector.newCancellationTokenSource(GradleConnector.java:95)
: 	at org.eclipse.jdt.ls.core.internal.managers.GradleProjectImporter.startSynchronization(GradleProjectImporter.java:152)
: 	at org.eclipse.jdt.ls.core.internal.managers.GradleProjectImporter.importDir(GradleProjectImporter.java:99)
: 	at org.eclipse.jdt.ls.core.internal.managers.GradleProjectImporter.lambda$0(GradleProjectImporter.java:91)
: 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
: 	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1083)
: 	at org.eclipse.jdt.ls.core.internal.managers.GradleProjectImporter.importToWorkspace(GradleProjectImporter.java:91)
: 	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.importProjects(ProjectsManager.java:132)
: 	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.access$1(ProjectsManager.java:126)
: 	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager$2.run(ProjectsManager.java:120)
: 	at org.eclipse.jdt.internal.core.BatchOperation.executeOperation(BatchOperation.java:38)
: 	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:733)
: 	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2289)
: 	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2316)
: 	at org.eclipse.jdt.core.JavaCore.run(JavaCore.java:5733)
: 	at org.eclipse.jdt.core.JavaCore.run(JavaCore.java:5690)
: 	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.initializeProjects(ProjectsManager.java:113)
: 	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.runInWorkspace(InitHandler.java:220)
: 	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
: 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
```

**Scenario 2:**
When I'm opening file from gradle project I'm getting prompt. I think it may be related to the above.
![class_path](https://user-images.githubusercontent.com/24554795/53284858-1d51df80-375a-11e9-9094-2b759b119c7f.png)

**Comment by piotrzarzycki21** [comment]
@joshtynjala do you see anything specific to the language server in those problems ? Do I need investigate them farther ?

**Comment by joshtynjala** [comment]
I assume that this issue will be resolved if I upgrade the Java language server. I'll try to do that in March.

**Comment by joshtynjala** [comment]
I just updated to jdt-language-server v0.34.0 in commit 90dc467156e1bde8a0914efd5cdb46075a528d50.

I updated the JDK in my settings to OpenJDK 11.0.2. Then, I restarted Moonshine and opened a Java Gradle project. I didn't get any errors, so this seems to be working correctly.
