### ISSUE TITLE
"Port Library failed to initialize" Error on Startup

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#476]
I started noticing an issue today with the macOS Moonshine build from the features/issue_449_streamline_with_moonshine_helper branch.  This message shows up on the console on startup

    : Error: Port Library failed to initialize: -1
    : Error: Could not create the Java Virtual Machine.
    : Error: A fatal exception has occurred. Program will exit.

And when I close the application, it is unusually slow to shut down (~10 seconds).

I first noticed this after I cleared the Git path from the Settings > GitHub menu, but I'm not sure if this is the exact cause.   This error triggered consistently for me, even if I set the Git path again.

**Comment by JoelProminic** [comment]
On further investigation, it seems that this error was caused by using an AdoptOpenJDK build with the OpenJ9 JVM. 

If I update Java Home in Moonshine, but an OpenJ9 JDK is still the default JDK for the macOS system, I get this error.  I think this may indicate that there is a problem with JAVA_HOME (see #456):

    : Mar 8, 2019 4:34:35 PM Failed to retrieve default libraries for /Library/Java/JavaVirtualMachines/adoptopenjdk-8-openj9.jdk/Contents/Home
    : Mar 8, 2019 4:34:35 PM Could not determine Java version for location /Library/Java/JavaVirtualMachines/adoptopenjdk-8-openj9.jdk/Contents/Home.
    : Mar 8, 2019 4:34:35 PM Could not determine Java version for location /Library/Java/JavaVirtualMachines/adoptopenjdk-8-openj9.jdk/Contents/Home.
    : Mar 8, 2019 4:34:35 PM Could not determine Java version for location /Library/Java/JavaVirtualMachines/adoptopenjdk-8-openj9.jdk/Contents/Home.
    : Mar 8, 2019 4:34:35 PM Could not determine Java version for location /Library/Java/JavaVirtualMachines/adoptopenjdk-8-openj9.jdk/Contents/Home.
    : Mar 8, 2019 4:34:35 PM Initialization failed 
    : Could not update project TestJavaMaven_0308 configuration
    : Java Model Exception: Core Exception [code 0] Could not update project TestJavaMaven_0308 configuration
    : 	at org.eclipse.jdt.internal.core.BatchOperation.executeOperation(BatchOperation.java:52)
    : 	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:736)
    : 	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2295)
    : 	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2322)
    : 	at org.eclipse.jdt.core.JavaCore.run(JavaCore.java:5810)
    : 	at org.eclipse.jdt.core.JavaCore.run(JavaCore.java:5767)
    : 	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.initializeProjects(ProjectsManager.java:117)
    : 	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.runInWorkspace(InitHandler.java:242)
    : 	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
    : 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
    : Caused by: org.eclipse.core.runtime.AssertionFailedException: null argument:
    : 	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:88)
    : 	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:76)
    : 	at org.eclipse.jdt.internal.launching.ClasspathShortener.<init>(ClasspathShortener.java:94)
    : 	at org.eclipse.jdt.internal.launching.ClasspathShortener.<init>(ClasspathShortener.java:89)
    : 	at org.eclipse.jdt.internal.launching.StandardVMRunner.getCommandLine(StandardVMRunner.java:468)
    : 	at org.eclipse.jdt.internal.launching.StandardVMRunner.run(StandardVMRunner.java:492)
    : 	at org.eclipse.jdt.launching.AbstractVMInstall.evaluateSystemProperties(AbstractVMInstall.java:398)
    : 	at org.eclipse.jdt.internal.launching.environments.ExecutionEnvironmentAnalyzer.isFoundation1_0(ExecutionEnvironmentAnalyzer.java:179)
    : 	at org.eclipse.jdt.internal.launching.environments.ExecutionEnvironmentAnalyzer.analyze(ExecutionEnvironmentAnalyzer.java:109)
    : 	at org.eclipse.jdt.internal.launching.environments.Analyzer.analyze(Analyzer.java:44)
    : 	at org.eclipse.jdt.internal.launching.environments.EnvironmentsManager.analyze(EnvironmentsManager.java:385)
    : 	at org.eclipse.jdt.internal.launching.environments.EnvironmentsManager.initializeCompatibilities(EnvironmentsManager.java:292)
    : 	at org.eclipse.jdt.internal.launching.environments.ExecutionEnvironment.init(ExecutionEnvironment.java:185)
    : 	at org.eclipse.jdt.internal.launching.environments.ExecutionEnvironment.getDefaultVM(ExecutionEnvironment.java:227)
    : 	at org.eclipse.jdt.internal.launching.JREContainerInitializer.resolveVM(JREContainerInitializer.java:179)
    : 	at org.eclipse.jdt.internal.launching.JREContainerInitializer.resolveVM(JREContainerInitializer.java:146)
    : 	at org.eclipse.jdt.internal.launching.JREContainerInitializer.initialize(JREContainerInitializer.java:63)
    : 	at org.eclipse.jdt.internal.core.JavaModelManager.initializeContainer(JavaModelManager.java:3195)
    : 	at org.eclipse.jdt.internal.core.JavaModelManager.getClasspathContainer(JavaModelManager.java:2116)
    : 	at org.eclipse.jdt.core.JavaCore.getClasspathContainer(JavaCore.java:3661)
    : 	at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:3156)
    : 	at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:3079)
    : 	at org.eclipse.jdt.internal.core.ClasspathEntry.validateClasspath(ClasspathEntry.java:1869)
    : 	at org.eclipse.jdt.internal.core.SetClasspathOperation.verify(SetClasspathOperation.java:125)
    : 	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:796)
    : 	at org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3568)
    : 	at org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3528)
    : 	at org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3541)
    : 	at org.eclipse.m2e.jdt.internal.AbstractJavaProjectConfigurator.configure(AbstractJavaProjectConfigurator.java:176)
    : 	at org.eclipse.m2e.core.project.configurator.AbstractLifecycleMapping.configure(AbstractLifecycleMapping.java:120)
    : 	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$3.call(ProjectConfigurationManager.java:508)
    : 	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$3.call(ProjectConfigurationManager.java:1)
    : 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
    : 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
    : 	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:501)
    : 	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.configureNewMavenProjects(ProjectConfigurationManager.java:288)
    : 	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$1.call(ProjectConfigurationManager.java:175)
    : 	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$1.call(ProjectConfigurationManager.java:1)
    : 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
    : 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
    : 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
    : 	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1336)
    : 	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.importProjects(ProjectConfigurationManager.java:143)
    : 	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.importProjects(ProjectConfigurationManager.java:133)
    : 	at org.eclipse.jdt.ls.core.internal.managers.MavenProjectImporter.importToWorkspace(MavenProjectImporter.java:153)
    : 	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.importProjects(ProjectsManager.java:137)
    : 	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.access$1(ProjectsManager.java:131)
    : 	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager$2.run(ProjectsManager.java:125)
    : 	at org.eclipse.jdt.internal.core.BatchOperation.executeOperation(BatchOperation.java:41)
    : 	... 9 more
    : Caused by: org.eclipse.core.runtime.CoreException: Could not update project TestJavaMaven_0308 configuration
    : 	at org.eclipse.m2e.core.project.configurator.AbstractLifecycleMapping.configure(AbstractLifecycleMapping.java:126)
    : 	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$3.call(ProjectConfigurationManager.java:508)
    : 	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$3.call(ProjectConfigurationManager.java:1)
    : 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
    : 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
    : 	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:501)
    : 	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.configureNewMavenProjects(ProjectConfigurationManager.java:288)
    : 	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$1.call(ProjectConfigurationManager.java:175)
    : 	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$1.call(ProjectConfigurationManager.java:1)
    : 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
    : 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
    : 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
    : 	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1336)
    : 	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.importProjects(ProjectConfigurationManager.java:143)
    : 	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.importProjects(ProjectConfigurationManager.java:133)
    : 	at org.eclipse.jdt.ls.core.internal.managers.MavenProjectImporter.importToWorkspace(MavenProjectImporter.java:153)
    : 	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.importProjects(ProjectsManager.java:137)
    : 	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.access$1(ProjectsManager.java:131)
    : 	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager$2.run(ProjectsManager.java:125)
    : 	at org.eclipse.jdt.internal.core.BatchOperation.executeOperation(BatchOperation.java:41)
    : 	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:736)
    : 	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2295)
    : 	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2322)
    : 	at org.eclipse.jdt.core.JavaCore.run(JavaCore.java:5810)
    : 	at org.eclipse.jdt.core.JavaCore.run(JavaCore.java:5767)
    : 	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.initializeProjects(ProjectsManager.java:117)
    : 	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.runInWorkspace(InitHandler.java:242)
    : 	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
    : 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
    : Caused by: org.eclipse.core.runtime.AssertionFailedException: null argument:
    : 	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:88)
    : 	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:76)
    : 	at org.eclipse.jdt.internal.launching.ClasspathShortener.<init>(ClasspathShortener.java:94)
    : 	at org.eclipse.jdt.internal.launching.ClasspathShortener.<init>(ClasspathShortener.java:89)
    : 	at org.eclipse.jdt.internal.launching.StandardVMRunner.getCommandLine(StandardVMRunner.java:468)
    : 	at org.eclipse.jdt.internal.launching.StandardVMRunner.run(StandardVMRunner.java:492)
    : 	at org.eclipse.jdt.launching.AbstractVMInstall.evaluateSystemProperties(AbstractVMInstall.java:398)
    : 	at org.eclipse.jdt.internal.launching.environments.ExecutionEnvironmentAnalyzer.isFoundation1_0(ExecutionEnvironmentAnalyzer.java:179)
    : 	at org.eclipse.jdt.internal.launching.environments.ExecutionEnvironmentAnalyzer.analyze(ExecutionEnvironmentAnalyzer.java:109)
    : 	at org.eclipse.jdt.internal.launching.environments.Analyzer.analyze(Analyzer.java:44)
    : 	at org.eclipse.jdt.internal.launching.environments.EnvironmentsManager.analyze(EnvironmentsManager.java:385)
    : 	at org.eclipse.jdt.internal.launching.environments.EnvironmentsManager.initializeCompatibilities(EnvironmentsManager.java:292)
    : 	at org.eclipse.jdt.internal.launching.environments.ExecutionEnvironment.init(ExecutionEnvironment.java:185)
    : 	at org.eclipse.jdt.internal.launching.environments.ExecutionEnvironment.getDefaultVM(ExecutionEnvironment.java:227)
    : 	at org.eclipse.jdt.internal.launching.JREContainerInitializer.resolveVM(JREContainerInitializer.java:179)
    : 	at org.eclipse.jdt.internal.launching.JREContainerInitializer.resolveVM(JREContainerInitializer.java:146)
    : 	at org.eclipse.jdt.internal.launching.JREContainerInitializer.initialize(JREContainerInitializer.java:63)
    : 	at org.eclipse.jdt.internal.core.JavaModelManager.initializeContainer(JavaModelManager.java:3195)
    : 	at org.eclipse.jdt.internal.core.JavaModelManager.getClasspathContainer(JavaModelManager.java:2116)
    : 	at org.eclipse.jdt.core.JavaCore.getClasspathContainer(JavaCore.java:3661)
    : 	at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:3156)
    : 	at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:3079)
    : 	at org.eclipse.jdt.internal.core.ClasspathEntry.validateClasspath(ClasspathEntry.java:1869)
    : 	at org.eclipse.jdt.internal.core.SetClasspathOperation.verify(SetClasspathOperation.java:125)
    : 	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:796)
    : 	at org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3568)
    : 	at org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3528)
    : 	at org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3541)
    : 	at org.eclipse.m2e.jdt.internal.AbstractJavaProjectConfigurator.configure(AbstractJavaProjectConfigurator.java:176)
    : 	at org.eclipse.m2e.core.project.configurator.AbstractLifecycleMapping.configure(AbstractLifecycleMapping.java:120)
    : 	... 28 more

We will create a new issue for OpenJ9 support later, if desired.
