### ISSUE TITLE
DirectoryNotEmptyException when creating a Grails project

### ISSUE THREAD

**Issue by joshtynjala** [prominic/Moonshine-IDE#960]
I get the following error in Moonshine when trying to create a new Grails project:

```
: Creating Grails application NewGrailsProject
: [1;31m| Error [22;39m/Users/joshtynjala/Development/Work/prominic/TestProjects/NewGrailsProject (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
: java.nio.file.DirectoryNotEmptyException: /Users/joshtynjala/Development/Work/prominic/TestProjects/NewGrailsProject
: 	at org.grails.cli.profile.commands.CreateAppCommand.handle(CreateAppCommand.groovy:268)
: 	at org.grails.cli.profile.commands.CreateAppCommand.handle(CreateAppCommand.groovy:385)
: 	at org.grails.cli.GrailsCli.executeCommandWithArgumentValidation(GrailsCli.groovy:286)
: 	at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:262)
: 	at org.grails.cli.GrailsCli.main(GrailsCli.groovy:159)
: [m[m
```

I suspect that this is happening because Moonshine creates the _.grailsproj_ file before asking the Grails tooling to create the Grails application. Perhaps saving the _.grailsproj_ file needs to be postponed until later in the project creating process.

My settings:

Default JDK: Temurin-11.0.13+8
JDK 8: Zulu 8.52.0.23-CA-macos-aarch64
Grails: 5.1.1
Gradle: 7.3.3

I suspect that I'm supposed to install older versions of Grails and/or Gradle, but I decided to approach this as an advanced user who already has these versions of the tools installed. Unfortunately, there are no clues about how to proceed from here.

Maybe Moonshine needs to do a version check of Grails and/or Gradle before trying to create a project. Or maybe these are versions are supposed to work, and it's just a bug that was previously unknown.

----

Additionally, I should also mention that I received a different error at first. Initially, I started out by setting the Grails and Gradle paths in Moonshine's settings. Then, when I tried to create a project, I got this error:

```
: Error: NewGrailsProject configures to build with JDK version is not present.
```

I was able to clear it up by also specifying JDK 8 in Moonshine's settings. Luckily, I suspected that JDK 8 was necessary based on some half-remembered previous discussions. However, users who are not familiar with Moonshine would probably never be able to guess that this is what the error message means. I think that this error message should probably specify that JDK 8 is required, and that the default JDK is not enough.

**Comment by rat-moonshine** [comment]
In a quick tests, the Grails project created successfully for me without an error. However, I assume I was using Grails 3.3.* that is why it ran successfully.
